name: CD

on:
  push:
    branches:
      - main

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build docker image
        run: docker build -t wjd030811/excel-importer .

      - name: publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wjd030811/excel-importer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: act10ns/slack@v1
          with:
            status: ${{ job.status }}
            steps: ${{ toJson(steps) }}
          if: always()